function  mainGenerateData(prefix,mid,seed)
%FUNCTION: mainGenerateData(prefix,mid,seed)
%   Main function to generate spike data.
%
% [Inputs]
%   prefix: the prefix of file name to store the generated data.
%
%   mid: ID number of data generative model. If mid=[], mid is reset at 0.
%   The data is generated by multi-timescale adaptive threshold (MAT) model
%   if mid=0.
%
%   seed: seed of random number generator. If seed=[], seed is reset at 0.

%%
%
% Constants
%

%%
%
% Initialize random number generator
%
RandStream.setDefaultStream(RandStream('mt19937ar','seed',seed));

%%
%
% Generate traning data
%

if(mid==1)
    [tbin,DELTA,Y,Rtrue,Wtrue,TAUtrue]=getSpikeDataFromMATmodel01;
elseif(mid==2)
    [tbin,DELTA,Y,Rtrue,Wtrue,TAUtrue]=getSpikeDataFromMATmodel02;
else
    [tbin,DELTA,Y,Rtrue,Wtrue,TAUtrue]=getSpikeDataFromMATmodel03;
    mid=3;
end

%%
%
% Exports the generate data to a file.
%

filename=sprintf('data/%s_%03d',prefix,seed);
save(filename,'mid','tbin','DELTA','Y','Rtrue','Wtrue','TAUtrue');
display(sprintf('Data is saved as %s.mat',filename));

end
