function print_AUCdescription(method,regFac,fFNAME,uFnum,inFiringUSE)
  spaceLen = length(sprintf('%s-%s-%s-%s-%s.mat',method, regFac{1}, ...
                            fFNAME, uFnum{F.from}, inFiringUSE{1}));

  fprintf(1,'LEGEND) TP:=True Positive, p:=positive, n:=negative\n')
  fprintf(1,['response func mat_file %s : (#)TP0  TPp  TPn  TPtotal'...
             ':(%%)TP0  TPp   TPn   TPtotal'...
             ': AUC threshold'...
             '\n'],...
          repmat(' ',[1 (spaceLen-28)]) )

