function S = load_ResFunc(tstatus,regFac,usedFrame,used_cnum, ...
                           varargin)

S = load([tstatus.savedirname,'/',tstatus.method,'-',...
          sprintf('%09.4f',regFac),...
          '-',regexprep(tstatus.inFiring,'(.*/)(.*)(.mat)','$2'),...
          sprintf('-%07d',usedFrame),...
          sprintf('-%03d',used_cnum),...
          '.mat'],varargin{:});

