function S = load_ResFunc(status,regFac,usedFrame,used_cnum,relDir, ...
                          varargin)

try
  S = load([status.savedirname,'/',relDir,'/',status.method,'-',...
            sprintf('%09.4f',regFac),...
            '-',regexprep(status.inFiring,'(.*/)(.*)(.mat)','$2'),...
            sprintf('-%07d',usedFrame),...
            sprintf('-%03d',used_cnum),...
            '.mat'],varargin{:});

catch err
  S = load([status.savedirname,'/',relDir,'/',status.method,'-',...
            sprintf('%09.4f',regFac),...
            '-',regexprep(status.inFiring,'(.*/)(.*)(.mat)','$2'),...
            sprintf('-%07d',usedFrame),...
            sprintf('-%03d',used_cnum),...
            '-CV1.mat'],varargin{:});
  %% CV? \in [1:status.crossVal]. CV1 is the most reliable.
end
