fprintf(1,'Please set outputfilename to your liking...\n')
uisave(who,...
sprintf('%s/%s_start_%s_%s.mat',...
                root_dir,date,...
                num2str(time.start(4)),num2str(time.start(5)))...
);

