tmp.switch=1;

  switch tmp.switch
    case 1
      opt.display = 1;
    case 2
      opt = struct();
    case 3
      %% Read dal.m for more details about parameters.
      % Don' work well.
      opt = struct( ...
          'aa',[],...
          'blks',[],...
          'tol',[],...
          'maxiter',[],...
          'eta',[],...
          'eps',[],...
          'eta_multp',[],...
          'eps_multp',[],...
          'solver',[],...
          'display',2,...
          'iter',20); % for dalprgl.m
  end