function  [kEKerWeight,kEbias,kEstatus,kEalpha,kDAL,kenv] = compare_KIM()


%% Prerequisite: 
%% 1) load *.mat generated by 'myest.m' or run 'myest.m'
%% 2) run compare_KIM.m
%  [kEKerWeight,kEbias,kEstatus,kEalpha,kDAL,kenv] = compare_KIM()
%%

global rootdir_;
global status;

%run([rootdir_ '/conf/conf_graph.m']);
kgraph = conf_graph();
kDAL = conf_DAL();
if ~exist('bases')
  %% Create GLM structure with default params
  bases = makeSimStruct_glm(0.01);
end
%readTrueConnection([roordir_ '/indir/KimFig1.con']);

tic
%%% ==< Kim >==
kDAL.speedup =0;
opt = kDAL.opt;
nbase = bases.ihbasprs.nbase;


load([rootdir_ '/indir/Simulation/data_sim_9neuron.mat']) % load 'X'

[L,kenv.cnum] = size(X);
DIV = 100;
%  kDrow = floor(L/3);
kDrow = floor(L/DIV);
kenv.genLoop = L;

plot_I(kgraph,kenv,X,' Firing from KIM''s neuron')

fprintf('\tGenerating Matrix for DAL\n');
[kD kpenalty] = gen_designMat(kenv,bases,X,kDrow);

% $$$ kpEKerWeight{1} = zeros(nbase,kenv.cnum);
% $$$ kpEbias{1} = 0;

if strcmp('dalprgl','dalprgl')
  pI= X((end - kDrow +1): end,:);
end
%% ==< init variables >==
kDAL.Drow = kDrow;

tmp.kmethod = 3;
kDAL.speedup =0;
kDAL.loop = 3;
kDAL.regFac = zeros(1,kDAL.loop); % kDAL.regFac: regularization factor.
if strcmp('setRegFac_auto','setRegFac_auto')
  if 1 ==1
    kDAL.regFac(1) = sqrt(nbase)*10; % kDAL.regFac: group LASSO parameter.
  else
    kDAL.regFac(1) = sqrt(nbase); % kDAL.regFac:
  end                                %  kDAL.regFac(1) = uint32(sqrt(kDAL.Drow)); % kDAL.regFac:
else
  kDAL.regFac(1) = 1; % kDAL.regFac: group LASSO parameter.
end
kDAL.div = 2;
%% ==</init variables >==

matlabpool(8);
for ii1 = 1:kDAL.loop % search appropriate parameter.
  fprintf(1,'\n\n == Regularization factor: %f == \n',kDAL.regFac(ii1));
  for i1to = 1:kenv.cnum % ++parallelization 
    switch  tmp.kmethod
      case 1
        %% logistic regression group lasso
        [kEKerWeight{i1to}, kEbias{i1to}, kEstatus{i1to}] = ...
            dallrgl( zeros(nbase,kenv.kenv.cnum), 0,...
                     kD, kpenalty(:,i1to), kDAL.regFac(ii1to),...
                     opt);
      case 2
        %% poisson regression group lasso: blk
        %% Returned pEKerWeight must be [10x9], not be [90x1] %++bug
        if kDAL.speedup == 1
          [kpEKerWeight{i1to}, kpEbias{i1to}, kpEstatus{i1to}] = ...
              dalprgl( kpEKerWeight{i1to}, kpEbias{i1to}, ...
                       kD, pI(:,i1to), kDAL.regFac(ii1),...
                       'blks',repmat(nbase,[1 kenv.cnum]));
        else
          [kpEKerWeight{i1to}, kpEbias{i1to}, kpEstatus{i1to}] = ...
              dalprgl( zeros(nbase*kenv.cnum,1), 0,...
                       kD, pI(:,i1to), kDAL.regFac(ii1),...
                       'blks',repmat(nbase,[1 kenv.cnum]));
        end

      case 3
        if kDAL.speedup == 1 
          [kpEKerWeight{i1to}, kpEbias{i1to}(ii1), kpEstatus{i1to}] = ...
              dalprgl( kpEKerWeight{i1to}, kpEbias{i1to}(ii1-1), ...
                       kD, pI(:,i1to), kDAL.regFac(ii1)...
                       ,opt);
        else
          [kpEKerWeight{i1to}, kpEbias{i1to}(ii1), kpEstatus{i1to}] = ...
              dalprgl( zeros(nbase,kenv.cnum), 0,...
                       kD, pI(:,i1to), kDAL.regFac(ii1)...
                       ,opt);
        end
    end
  end

  kDAL.speedup = 1;
  if ii1 < kDAL.loop
    %        kDAL.regFac(ii1+1) = kDAL.regFac(ii1)/5;
    kDAL.regFac(ii1+1) = kDAL.regFac(ii1)/kDAL.div;
  end

  switch tmp.kmethod
    case 1
      for i1to = 1:kenv.cnum
        for i2from = 1:kenv.cnum
          kEalpha{ii1}{i1to}{i2from} = (bases.ihbasis* kEKerWeight{i1to}(:,i2from));
        end
      end
      
    case 3
      for i1to = 1:kenv.cnum
        for i2from = 1:kenv.cnum
          kEalpha{ii1}{i1to}{i2from} = (bases.ihbasis* kpEKerWeight{i1to}(:,i2from));
        end
      end
      
    otherwise
  end

% $$$   if graph.PLOT_T == 1
% $$$     plot_Ealpha(kenv,graph,Ealpha{ii1},...
% $$$                 strcat(['Kim:dalprgl:kDAL regFac'],num2str(kDAL.regFac(ii1))));
% $$$   end
end
matlabpool close

kEKerWeight = kpEKerWeight;
kEbias = kpEbias;
kEstatus = kpEstatus;

%%% ==</Kim >==
status.time.estimate_TrueValue_KIM = toc;
fprintf(1,'%s',status.time.estimate_TrueValue_KIM);


if kgraph.PLOT_T == 1
  for i1 = 1:length(kDAL.regFac)
    plot_Ealpha(kenv,kgraph,kEalpha{i1},...
                strcat('dallrgl:DAL regFac=  ', num2str(kDAL.regFac(i1))));
  end
end
