if 1 == 0
  opt.display = 1;
elseif 1 == 0
opt = struct();
else
  %% Read dal.m for more details about parameters.
opt = struct( ...
'aa',[],...
'blks',[],...
'tol',[],...
'maxiter',[],...
'eta',[],...
'eps',[],...
'eta_multp',[],...
'eps_multp',[],...
'solver',[],...
'display',2,...
'iter',20); % for dalprgl.m
end